server:
  port: 8080
spring:
  application:
    name: jd-ticketing-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
security:
  jwt:
    secret-key: cybertek
springdoc:
  swagger-ui:
    path: /swagger-ui.html
# localhost:8080/swagger-ui.html sayfası openApi sayfamız oluyor...